<?php
define("_ACCUEIL", "ترحيب");
define("_Apropos", "حول");
define("_SERVICES", "الخدمات");
define("_PROJETS", "مشاريع");
define("_CONTACT", "الاتصال");
define("_para", "خزانة متخصصة في تقويم الأسنان في بني ملال");
define("_ra","ابتسم ، وتناول الطعام واجتماعيا دون إزعاج.");
define("_famille","تقويم الأسنان لجميع أفراد الأسرة");
define("_Arabe", "العربية");
define("_Français", "الفرنسية");
define("_enfant","الأطفال في سن المراهقة والكبار.");
// define("_Àproposdemoi", "About me");
// define("_Sujet", "Subject");
// define("_Email", " Email:");
// define("_Profile", "Profile:");
// define("_Nom", "Name:");
// define("_Téléphone", "Phone:");
// define("_ProvincedELJADIDA","District D'EL JADIDA");
// define("_civil","Internship at the civil status department.");
// define("_sté","Sté sud relax.");
// define("_Réceptionniste","Receptionist.");
// define("_GROUPE","GROUPE OCP EL JADIDA");
// define("_Stageengestion","Internship in the management support department.");
// define("_départementsupport","département support.");
// define("_Présent","Présent");
// define("_developmentweb","development web.");
// define("_tech","Technician in computerized business management.");
// define("_lycee","High School Imam El Boukhari");
// define("_svt","Baccalaureate level Option << Science of life and earth >>.");
// define("_env","Send Us A Message");
// define("_full","full stack developer");
// define("_msg","Send email");
// define("_Votre","Your Email");
// define("_Sjt","Subject");
// define("_Message","Message");
// define("_VotreNom","Your Name");
// define("_Expérience","Experience");
// define("_Formation","Education");
// define("_Skills","Skills");
// define("_Script","script.js");
?>
